### ISSUE TITLE
[Feature] Compatibility with AttractMode (or other launchers?)

### ISSUE THREAD

**Issue by placeboyue** [oblivioncth/FIL#2]
I guess the way both launchers work are not THAT different so this could be adapted to work with others too. Or just generate a generic list/xml or whatever this does, so i can then edit to suit AM needs and use it.

**Comment by oblivioncth** [comment]
The XMLs that it generates are very specific to LB.

I haven't used AttractMode or other front ends, and making this program work with it/them would require an overhaul to about half of the design, but I am somewhat interested in making it happen, as once I implemented a more modular design for the importee, it would be much easier to add support for additional frontends.

Sadly I just put a ton of work into overhauling CLIFp, with there being an additional request to port it to Linux as well, so I'd like to step away from this project for a bit.

I'm definitely going to take a look at AttractMode's formats and get around to this eventually, but I can't promise any kind of time frame.

**Comment by oblivioncth** [comment]
@placeboyue 

Alright well it may have literally taken a year, but I just released the first version of the tool that's on the overhauled code base, designed for adding support for an arbitrary number of frontends.

It remains to be seen how complete (in terms of functionality and metadata) imports will be on frontends other than LaunchBox since the tool will ultimately be limited by their capabilities and I have no experience with anything else, so I have no sense what to expect until I start trying.

Is AttractMode still the launcher you'd be most interested in seeing supported? From what I remember glancing at a year ago I do think I foresaw a couple potential issues since its so substantially different from how LaunchBox handles things, but I imagine each one will probably have unique challenges anyway.

**Comment by placeboyue** [comment]
Yeah i still use attract mode and i wouldn't mind if this was somehow compatible! 
I'd understand if you focus on more popular frontends tho. I just went with this one and stuck with it because it just works, but I dunno what everyone else is using, or why.

**Comment by oblivioncth** [comment]
> Yeah i still use attract mode and i wouldn't mind if this was somehow compatible! I'd understand if you focus on more popular frontends tho. I just went with this one and stuck with it because it just works, but I dunno what everyone else is using, or why.

I mean it's popular enough, I certainly know it exists. I just remember that since its so focused on emulators it seemed like it might be tricky just adding in stuff by editing the data files directly. It's been so long though I really don't remember for sure.

Since I don't use any others I'm not motivated to try and get any particular one worked, so I mind as well at least start with AttractMode since its been requested lol. If for some unlikely reason it ends up being a nightmare I can always shelf it and come back to it after doing another one.

**Comment by oblivioncth** [comment]
Alright alpha tester, when you get a chance give this build a shot: https://github.com/oblivioncth/FIL/suites/7640154976/artifacts/317751499

You also probably want to look at the AttractMode part of this section of the README on the AM support branch so you have an idea of what to expect:
https://github.com/oblivioncth/FIL/tree/feature/attractmode_support#launcher-specific-details

**Comment by oblivioncth** [comment]
Alright well at this point it's merged in because I felt that, at least for a first go, it works well enough.

Still do let me know though if you get around to trying it as I can always use feedback.

Completed via #12.
