### ISSUE TITLE
[BUG] Images not copied into Launchbox Images folder

### ISSUE THREAD

**Issue by dsync89** [oblivioncth/FIL#44]
### STOP
If this is a bug that actually pertains to CLIFp(the command-line tool paired with this importer) please use the issue tracker for [that repository](https://github.com/oblivioncth/CLIFp/issues) instead.

### When submitting a bug please use this template:
**Describe the bug**
When selecting 'Copy' as the Image Mode, the images (screenshots) for the platform is not copied to Launchbox Images folder. Some platform has images copied, but just a few of them. The metadata does however imported.

**To Reproduce**
1. Select `Copy` Image Mode
2. Start Import

**Expected behavior**
All screenshots images should be copied into Launchbox Images\<Platform> folder.

**Screenshots**

The `Flash` platform has over 100k games,
![image](https://github.com/oblivioncth/FIL/assets/12208390/bd0e94ea-3d8e-4525-9dd5-ac83ac3de2b6)

But its Images folder only shows
![image](https://github.com/oblivioncth/FIL/assets/12208390/dbcde275-0d0d-4c03-83cc-06f664795639)

**Version (please complete the following information):**
- FIL version: FIL_v0.7.4_Windows_Static_x64
- CLIFp version (if different from the included version)
- Flashpoint version (including whether you are using Ultimate or Infinity): Flashpoint 12.1 Ultimate

**Additional context**

**Comment by oblivioncth** [comment]
You most likely downloaded Ultimate via the updater tool, as there's a bug with it where most images were accidentally placed into a second sub-folder. When you look at the games in the regular launcher it's actually downloading them on the fly because in FP12 Ultimate the onDemandImages preference is set to true even though it's not Infinity.

FP12 Ultimate has had a number of issues.

You can fix the problem by moving the lower Images folder into its parent so that they're merged.

See the following for more context: https://forums.launchbox-app.com/topic/56845-flashpoint-importer-for-launchers/?do=findComment&comment=448094

This was reported to the FP12 but hasn't been formally acknowledged yet.

**Comment by dsync89** [comment]
Thanks for pointing it out @oblivioncth ! FYI I was downloading FP Ultimate 12.1 instead of Infinity using FP Updater because it was giving me tons of File unable to download error near the end. So I ended up getting the huge 1.5T tar  version and extract it.

Indeed I checked and there is a nested Images folder under `Data\Images\Images`, which seems to be the complete one. Strange that the parent `Data\Images` still have some sizes. From the sizes it seems like the nested one `Data\Images\Images` is the correct ones, not sure why it ended up there, maybe FP Launcher did that? I assume FIL will import images from `Data\Images` instead of the nested one. I'll try to move the nested folder one level up and re-run FIL importer and see how it goes.

Still ongoing but here's the progress. 
![image](https://github.com/oblivioncth/FIL/assets/12208390/f099107b-a227-4805-8ece-3f000ef67541)

**Comment by oblivioncth** [comment]
It's due to an error with the manifest that they used when setting up Ultimate 12, so it just comes like that with the issue out of the box. It's nothing the launcher is doing.

Both the regular launcher and FIL expect the images to not be nested like that so all you need to do is cut the lower image folder and paste it one directory up next to the top level one and say yes to the prompts that note they will be merged. Then everything will work.

As I was saying earlier, the only reason you're even seeing any images with the regular launcher at all is because it's downloading duplicates in the correct location on the fly as if it was Infinity because they didn't turn that off for Ultimate.

**Comment by oblivioncth** [comment]
Closing this since this is no longer an issue with FP13 Ultimate.
